Childer:  # Thinbloods
  bloodPotency: 0
  humanity: 7
  experience: 0
  generations: [14, 15, 16]

Neonate:
  bloodPotency: 1
  humanity: 7
  experience: 15
  generations: [12, 13]

Ancilla:
  bloodPotency: 2
  humanity: 6
  experience: 35
  generations: [10, 11]
